[package]
name = "cs_project-rust"
version = "0.1.0"
authors = ["cumet04 <medalhkr@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.14.0"
glfw = "0.37.0"
cgmath = "0.17.0"
image = "0.23.4"
include_dir = "0.6.0"
