version: '3'
services:
  rust:
    build:
      context: .
    command: /bin/sh
    tty: true
    volumes:
      - ".:/app"
      - "/home/app"
      - "~/.ssh:/home/app/.ssh"
      - "~/.gitconfig:/home/app/.gitconfig"
